version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "flask*"
    ignore:
      - dependency-name: "flask"
        versions: ["< 0.12"]
